# Generated by Django 3.0.6 on 2020-05-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(default='익명의작성자', max_length=120),
        ),
    ]
